
export const GET_DATA_PRODUCTS_BEGIN = "GET_DATA_PRODUCTS_BEGIN";
export const GET_DATA_PRODUCTS_SUCCESS = "GET_DATA_PRODUCTS_SUCCESS";
export const GET_DATA_PRODUCTS_FAIL = "GET_DATA_PRODUCTS_FAIL";

export const GET_DATA_PRODUCTS_SEARCH_BEGIN = "GET_DATA_PRODUCTS_SEARCH_BEGIN";
export const GET_DATA_PRODUCTS_SEARCH_SUCCESS = "GET_DATA_PRODUCTS_SEARCH_SUCCESS";
export const GET_DATA_PRODUCTS_SEARCH_FAIL = "GET_DATA_PRODUCTS_SEARCH_FAIL";

export const GET_DATA_PRODUCTS_DETAIL_BEGIN = "GET_DATA_PRODUCTS_DETAIL_BEGIN";
export const GET_DATA_PRODUCTS_DETAIL_SUCCESS = "GET_DATA_PRODUCTS_DETAIL_SUCCESS";
export const GET_DATA_PRODUCTS_DETAIL_FAIL = "GET_DATA_PRODUCTS_DETAIL_FAIL";

export const GET_DATA_PRODUCTS_FILTER_BEGIN = "GET_DATA_PRODUCTS_FILTER_BEGIN";
export const GET_DATA_PRODUCTS_FILTER_SUCCESS = "GET_DATA_PRODUCTS_FILTER_SUCCESS";
export const GET_DATA_PRODUCTS_FILTER_FAIL = "GET_DATA_PRODUCTS_FILTER_FAIL";

export const POST_KEYWORD_DATA_PRODUCTS_BEGIN = "POST_KEYWORD_DATA_PRODUCTS_BEGIN";
export const POST_KEYWORD_DATA_PRODUCTS_SUCCESS = "POST_KEYWORD_DATA_PRODUCTS_SUCCESS";
export const POST_KEYWORD_DATA_PRODUCTS_FAIL = "POST_KEYWORD_DATA_PRODUCTS_FAIL";